SUBSTRATE_MAP = {
    'Light': 'Light', 
    'Xylose': 'Sugars', 
    'Tryptophan': 'Amino acid medium', 
    'Cellulose': 'Lignocellulose', 
    'Lignocellulose': 'Lignocellulose', 
    'CO2': 'Gas', 
    'Syngas': 'Gas', 
    'Saccharides': 'Sugars', 
    'VFA_s': 'Short-chain fatty acids', 
    'Wastewater sludge': 'Waste', 
    'CO': 'Gas', 
    'Glucose': 'Sugars', 
    'Meat extract': 'Waste', 
    'Industrial waste': 'Waste', 
    'Amino acid medium': 'Amino acid medium', 
    'Food waste': 'Waste', 
    'Glycerol': 'Alcohols', 
    'Phenanthrene': 'Other substrate', 
    'Methanol_s': 'Alcohols', 
    'Starch': 'Sugars', 
    'Sucrose': 'Sugars',
    'Organic waste': 'Waste', 
    'Ethanol': 'Alcohols', 
    'Acetate': 'Short-chain fatty acids', 
    'Crude oil': 'Crude oil', 
    'Arabinose': 'Sugars', 
    'Antibiotic fermentation residue': 'Waste', 
    'Activated sludge': 'Waste', 
    'Galactose': 'Sugars', 
    'Bovine milk': 'Complex media', 
    'Amino acids': 'Amino acid medium', 
    'Glycerin': 'Alcohols', 
    'Sludge compost': 'Waste', 
    'Fructose': 'Sugars', 
    'Lupin flour': 'Complex media', 
    'Manure compost': 'Waste'
}

PRODUCT_MAP = {
    'Antilisterial compounds': 'Antibiotics', 
    '7-methylxanthine': 'Pharmaceuticals', 
    'L-lysine': 'Amino acids', 
    'Fructo-oligosaccharide': 'Polysaccharides', 
    'Caproate': 'Carboxylic acids and esters', 
    'Glycosides': 'Other', 
    'coniferyl alcohol': 'Phenols', 
    'O-methylated phenylpropanoids': 'Pharmaceuticals', 
    'MCFA': 'Carboxylic acids and esters', 
    'Hydrogen': 'Hydorgen gas', 
    'caffeyl alcohol': 'Phenols', 
    '3-hydroxypropionic acid': 'Carboxylic acids and esters', 
    'Polysaccharide': 'Polysaccharides', 
    'Polyhydroxyalkanoate': 'Polyester polymers', 
    'Bacterial cellulose': 'Cellulose', 
    'Indigo': 'Dyes and pigments', 
    'Anthocyanins': 'Dyes and pigments', 
    'SCFA': 'Carboxylic acids and esters', 
    '3-hydroxybenzoic acid': 'Phenols', 
    'lovastatin': 'Pharmaceuticals', 
    'Antibodies': 'Proteins', 
    'Rosmarinic acid': 'Phenols', 
    'Butanol': 'Primary alcohols', 
    'Fumaric acid': 'Carboxylic acids and esters', 
    'Microbial proteases': 'Proteins', 
    'Recombinant protein': 'Proteins', 
    'Glucose_p': 'Metabolites to support growth', 
    'VFA': 'Carboxylic acids and esters', 
    'Ethanol': 'Primary alcohols', 
    'Pyranoanthocyanins': 'Phenols', 
    'Itaconic acid': 'Carboxylic acids and esters', 
    'P-coumaric acid': 'Carboxylic acids and esters', 
    'Methanol_p': 'Primary alcohols', 
    'Electricity': 'Electricity', 
    'Lipopeptides': 'Proteins', 
    'Phenol': 'Phenols', 
    'Biosurfactants': 'Other', 
    'Resveratrol': 'Phenols', 
    'Biomass': 'Biomass', 
    'Cercosporin': 'Pharmaceuticals', 
    'Pharmaceutically active compounds': 'Pharmaceuticals', 
    'Caffeic acid': 'Phenols', 
    'Vitamins': 'Metabolites to support growth', 
    'Butyrate': 'Carboxylic acids and esters', 
    'Flavonoids': 'Phenols', 
    'Monacolin': 'Pharmaceuticals', 
    'Glionitrin B': 'Pharmaceuticals', 
    'Hyaluronic acid': 'Pharmaceuticals', 
    '1,3-Propanediol': 'Glycols', 
    'Propionate': 'Carboxylic acids and esters', 
    'PHB': 'Polyester polymers', 
    'Butyl acetate': 'Carboxylic acids and esters', 
    'Fatty acid': 'Carboxylic acids and esters',
    'Lactate': 'Carboxylic acids and esters', 
    'Caproic acid': 'Carboxylic acids and esters', 
    'Organic acids': 'Carboxylic acids and esters', 
    'Siderophores': 'Bacterial extracellular compounds', 
    'Bioflocculant': 'Bacterial extracellular compounds', 
    'Fermented food product': 'Fermented food products', 
    'Lactic acid': 'Carboxylic acids and esters',  
    'Glutamic acid': 'Amino acids', 
    'SCCA': 'Carboxylic acids and esters', 
    'Methane': 'Methane', 
    'SCOA': 'Carboxylic acids and esters'}